### ISSUE TITLE
Mud/Sediment ToDo List (with 2phase)

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#771]
Debris Basin
The intent is to have an inflow element enter a basin and the hydrograph will fill the volume before it can move downstream.
The cell number in the debris basin is the same cell in inflow.dat that will fill the basin.
 
Sediment size fraction and sediment rating curve

- [x] Change percentage to Percent Finer

- [x] #905

 
Rigid bed

- [x] I think we can digitize the rigid bed layer directly from the map and then use a schematize button on the window to add those cells to the Sediment Tables.

 

- [x] Use the name of the sediment transport equation instead of the equation ID.

 
2phase flow difference

- [x] include M line
- [x] include C line
- [x] Mud in cont.dat = 2
 
Tabs

- [x] Mud / Debris Flow
- [x] Sediment Transport
- [x] 2Phase Flow
- [x] None
 
Add a third line to control variable dialog

- [x] Mud/Debris =  imud switch = 1
- [x] Sediment Transport = Ised = 1.  This one is mutually exclusive from the mud switch.
- [x] 2-phase flow imud = 2 and ised = 1 is automatically written.

**Comment by FLO-2DKaren** [comment]
@FLO-2DJJ @FLO-2DNoemi Let's be sure to use this list to help us with our meeting today.

**Comment by FLO-2DKaren** [comment]
2 phase example
https://flo-2d.sharefile.com/d-s9a9e5c77b9254a3881f362d5d263720a

**Comment by FLO-2DJJ** [comment]
@FLO-2DNoemi  @FLO-2DKaren 

I'm going to hide layer "Mud Areas" of Sediment Transport. Explanation:

Debris basin: it should be a single cell with a volume (line 5 of SED.DAT):
Line 5: SEDCHAR = ‘D’ JDEBNOD DEBRISV
Just one cell.
However the plugin has a strange way of defining its geometry using a polygon in layer "Mud Areas" (for table "mud_areas").  
In reality that "mud_areas" table is used internally during the mud functionally when reading/writing SED.DAT and in the mud/sediment transport dialog, but there is no need for the user to create polygons explicitly.
I'm going to hide that layer for the user.

**Comment by FLO-2DJJ** [comment]
Also the name of layer "Mud Cells" (plural) was changed to "Mud Cell"
(single) in layers panel (under Sediment Transport tables) to reflect that
it only contains one feature.


Juan Jose Rodriguez
FLO-2D Software
www.flo-2d.com
***@***.***

**Comment by FLO-2DNoemi** [comment]
JJ,

I think these changes are OK, we can take a look together at this tomorrow.

N

**Comment by FLO-2DKaren** [comment]
@FLO-2DJJ Can we go over this on Friday. I think all of this is complete.

**Comment by FLO-2DJJ** [comment]
@FLO-2DNoemi @FLO-2DKaren 
All tasks in this issue has been addressed. 
Due to the complexity of the sediment transport functionality extensive testings may be required, but all the tests done so far has been passed.
